### PR TITLE
ipapprox

### PR DESCRIPTION
**Pull request by bluewww**
Add `src_files.yml` and `ips_list.yml` for ipapprox.

### CODE REVIEW

**Comment by bluewww** [comment]
To be merged after #5

**Review by zarubaf — APPROVED** [review]
LGTM. Pls, merge at your discretion.

**Review by meggiman — APPROVED** [review]
LGTM

**Comment by bluewww** [comment]
Will delete this (`ipapprox`) branch after we have fixed `pulp_soc`

**Pull request merged**
